<?php

function node_map_node_insert($node)
{
  $new_node=array();
  $field_name=array('title','body');
  $nam=array();
  foreach($field_name as $values)
  {
    //print_r($node->$values);
    $nam[$values]=$node->$values;
    if(isset( $node->values))
    {
      
    }
  }
  // web serive  calling code starts
    $request_url = 'http://localhost/site2/user/login';
     $user_data = array(
    'username' => 'kellton',
    'password' => 'password123',
  );
 $user_data = http_build_query($user_data);
 $curl = curl_init($request_url);
  curl_setopt($curl, CURLOPT_HTTPHEADER, array('Accept: application/json')); // Accept JSON response
  curl_setopt($curl, CURLOPT_POST, 1); // Do a regular HTTP POST
  curl_setopt($curl, CURLOPT_POSTFIELDS, $user_data); // Set POST data
  curl_setopt($curl, CURLOPT_HEADER, FALSE);  // Ask to not return Header
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($curl, CURLOPT_FAILONERROR, TRUE);

  $response = curl_exec($curl);
  $http_code = curl_getinfo($curl, CURLINFO_HTTP_CODE);
  // Check if login was successful
  if ($http_code == 200) {
    // Convert json response as array
    $logged_user = json_decode($response);
  }
  else {
    // Get error msg
    $http_message = curl_error($curl);
    die($http_message);
  }
  $text=array();
  $text['namit']="namit garg is a";
  $final_data=http_build_query($text);
  $request_url = 'http://localhost/site2/nodeapi/create_node';
    // Define cookie session
  $cookie_session = $logged_user->session_name . '=' . $logged_user->sessid;
  // cURL
  $curl = curl_init($request_url);
  curl_setopt($curl, CURLOPT_HTTPHEADER, array('Accept: application/json')); // Accept JSON response
  curl_setopt($curl, CURLOPT_POST, 1); // Do a regular HTTP POST
  curl_setopt($curl, CURLOPT_POSTFIELDS, $final_data); // Set POST data
  curl_setopt($curl, CURLOPT_HEADER, FALSE);  // Ask to not return Header
  curl_setopt($curl, CURLOPT_COOKIE, "$cookie_session"); // use the previously saved session
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($curl, CURLOPT_FAILONERROR, TRUE);
  $response = curl_exec($curl);
  
  $http_code = curl_getinfo($curl, CURLINFO_HTTP_CODE);
  // Check if login was successful
  if ($http_code == 200) {
    // Convert json response as array
    $node = json_decode($response);
  }
  else {
    // Get error msg
    $http_message = curl_error($curl);
    die($http_message);
  }

}